<?php

/**
 * Implements hook_menu_alter().
 */
function embed_twitter_feed_menu_alter(&$items) {

  $items['admin/config/embed_twitter_feed'] = array(
    
    'title' => 'Configure Twitter API',
    'description' => 'connecting this site to others',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'embed_twitter_feed_config_form'
    ) ,
    'type' => MENU_NORMAL_ITEM,
    
    'access arguments' => array(
      'configure social media api settings'
    ),
    'file' => 'embed_twitter_feed.admin.inc',
    'file path' => drupal_get_path('module', 'embed_twitter_feed'), // fails without this - which should be the default? 
  );
  return $items;
}


  /**
   * Implements hook_permission().
   */
  function embed_twitter_feed_permission() {
    return array(
      'configure social media api settings' =>  array(
        'title' => t('Manage social media API details'),
        'description' => t('User can edit API details for Twitter etc'),
      ),
    );
  }


  /**
   * Implements hook_cron().
   */
  function embed_twitter_feed_cron() {
     embed_twitter_feed_get_tweets();
  }



/**
 * get the latest tweets! - 
 * generally this would be run from a cron - but can be called from anywhere 
 */
function embed_twitter_feed_get_tweets(){
     $opts = variable_get('embed_twitter_feed_settings', array());

      if (empty($opts) || empty($opts['defaults'])) {
        return false;
      }
      
      $auth = array('consumer_key' => $opts['defaults']['consumer_key'], 'consumer_secret' => $opts['defaults']['consumer_secret']);

      

      $timelines = $opts['defaults']['timelines'];
      $timeline_options = array();
      if(!empty($timelines)){
        
        $screen_name = $opts['defaults']['timelines'];
        $count = !empty($opts['defaults']['tweetcount'])?$opts['defaults']['tweetcount']:20;
        $retweets = !empty($opts['defaults']['retweets'])?$opts['defaults']['retweets']:false;
        
        //be careful - the option is exclude replies - but our interface asks for 'include' so we want a truthy to exclude, a falsey to include
        $replies = empty($opts['defaults']['replies'])?$opts['defaults']['replies']:true;


        $timeline_options['default'] = array(
          'api_options'=>array(
            'screen_name' => $screen_name,
            'count' => $count,
            'rts'=> $retweets,
            'exclude_replies' => $replies
            )
        );
      }
      

      // get the list of timelines from other modules via hook_embed_twitter_feed_timeline();
      drupal_alter('embed_twitter_feed_timeline', $timeline_options );

      foreach($timeline_options as $source=>$loadopts){
          $twitter = new OnTheWeb_Twitter( $auth, 'OnTheWeb_Adaptor_Drupal');

          $api_options = array_merge($timeline_options['default']['api_options'], $loadopts['api_options']);

          $tweets = $twitter->get_user_timeline($api_options);
          
          // do a callback if one has been set. 
          if(isset($loadopts['callback_context'])){
            drupal_alter('embed_twitter_feed_timeline_save', $tweets, $loadopts['callback_context']);
          }
          if($source == 'default'){
            variable_set('embed_twitter_feed_data_default', $tweets);
          }
      }
      
}

